### ISSUE TITLE
    except ValueError, e:

### ISSUE THREAD

**Issue by hariharan382** [305engineering/Inkscape#32]
Traceback (most recent call last):
  File "raster2laser_gcode.py", line 37, in <module>
    import png
  File "C:\Program Files\Inkscape\share\inkscape\extensions\Inkscape-master\png.py", line 1885
    except ValueError, e:
                     ^
SyntaxError: invalid syntax

i am getting this error when trying to use gcode extension,i have no idea how to edit it since it is 2500 line of code

**Comment by DomBDev** [comment]
im having this same error

**Comment by WhamBamSystems** [comment]
I'm getting the same error with Inkscape 1.1 on a Mac.  Does this plugin work for version 1.1?

**Comment by BCChad** [comment]
I'm trying to overcome this as well - in my researching ValueError, it seems that it should have no arguments, simply ValueError:
I have removed the ", e" and made progress in debugging, but encountered further errors elsewhere. (newbie at Python, trying my best...).

**Comment by rktech-de** [comment]
the above message, that I have added a commit to the issue 32 is wrong. what I did is implementing the pull request https://github.com/305engineering/Inkscape/pull/23, it was only a typo in my commit massage, sorry

**Comment by ghost** [comment]
Another DEAD project, Thanks to Python3.

**Comment by WhamBamSystems** [comment]
Hello,
Is there something Wham Bam related I can help you with?
thanks

my best,

Peter
founder Wham Bam Systems LLC

290 North Federal Highway
Hollywood, FL, 33020   USA
+1 (954) 391-8921

Wham Bam thanks you ma’am!

www.whambamsystems.com
***@***.***



[whambamhorizshadowsmall.jpg]

On Apr 7, 2023, at 8:53 AM, Terak 8510 ***@***.***> wrote:



Another DEAD project, Thanks to Python3.

**Comment by ghost** [comment]
![Screenshot_2023-04-07_07-03-42](https://user-images.githubusercontent.com/101630460/230622188-4d2c9fee-5268-4a28-b9a6-7756af822e90.png)

![Screenshot_2023-04-07_07-02-15](https://user-images.githubusercontent.com/101630460/230622232-eaa84738-5e13-4973-baf0-a6aaf5f40e4b.png)

**Comment by rktech-de** [comment]
Maybe this helps, I have get my version running with Inkscape 1.1 (Python3) with this change in png.py
https://github.com/rktech-de/Inkscape/blob/master/png.py

**Comment by ghost** [comment]
Well i am running inkscape 1.0.2-4 and will stay that way, until debian bullseye
finalizes at oldstable.

![Screenshot_2023-04-07_20-06-41](https://user-images.githubusercontent.com/101630460/230700776-c1a7eb15-3782-45b8-885b-ba6683912010.png)

**Comment by rktech-de** [comment]
Hi, the png.py file shouldn't have any "DOCTYPE" tag, maybe you have downloaded the github website and not only the Python code of the png.py file? 
best you download the full projekt zip https://github.com/rktech-de/Inkscape/archive/refs/heads/master.zip and copy the png.py file (or try it with my fork)
